vim.cmd.hi 'MarkviewTableHeader guifg=#89dcec'
vim.cmd.hi 'MarkviewTableBorder guifg=#89b4fb'
vim.cmd.hi 'MarkviewTableAlignCenter guifg=#89dcec'
vim.cmd.hi 'MarkviewTableAlignLeft guifg=#89dcec'
vim.cmd.hi 'MarkviewTableAlignRight guifg=#89dcec'
vim.cmd.hi 'MarkviewListItemStar guifg=#89b4fb'
vim.cmd.hi 'MarkviewListItemPlus guifg=#a6e3a2'
vim.cmd.hi 'MarkviewListItemMinus guifg=#f9e2b0'
vim.cmd.hi 'MarkviewLatexSubscript cterm=italic gui=italic guifg=#a1947b'
vim.cmd.hi 'MarkviewLatexSuperscript cterm=italic gui=italic guifg=#6f9473'
vim.cmd.hi 'MarkviewGradient1 guifg=#cdd6f4'
vim.cmd.hi 'MarkviewGradient2 guifg=#c5d2f4'
vim.cmd.hi 'MarkviewGradient3 guifg=#bdcef5'
vim.cmd.hi 'MarkviewGradient4 guifg=#b6caf6'
vim.cmd.hi 'MarkviewGradient5 guifg=#aec6f7'
vim.cmd.hi 'MarkviewGradient6 guifg=#a7c3f7'
vim.cmd.hi 'MarkviewGradient7 guifg=#9fbff8'
vim.cmd.hi 'MarkviewGradient8 guifg=#98bbf9'
vim.cmd.hi 'MarkviewGradient9 guifg=#90b7fa'
vim.cmd.hi 'MarkviewGradient10 guifg=#89b4fb'
vim.cmd.hi 'MarkviewHeading6 guifg=#b4beff guibg=#434662'
vim.cmd.hi 'MarkviewHeading6Sign guifg=#b4beff'
vim.cmd.hi 'MarkviewHeading5 guifg=#74c7ed guibg=#33485d'
vim.cmd.hi 'MarkviewHeading5Sign guifg=#74c7ed'
vim.cmd.hi 'MarkviewHeading4 guifg=#a6e3a2 guibg=#404f4b'
vim.cmd.hi 'MarkviewHeading4Sign guifg=#a6e3a2'
vim.cmd.hi 'MarkviewHeading3 guifg=#f9e2b0 guibg=#544f4e'
vim.cmd.hi 'MarkviewHeading3Sign guifg=#f9e2b0'
vim.cmd.hi 'MarkviewHeading2 guifg=#fab388 guibg=#554344'
vim.cmd.hi 'MarkviewHeading2Sign guifg=#fab388'
vim.cmd.hi 'MarkviewHeading1 guifg=#f38ba9 guibg=#53394c'
vim.cmd.hi 'MarkviewHeading1Sign guifg=#f38ba9'
vim.cmd.hi 'MarkviewCode guibg=#28283d'
vim.cmd.hi 'MarkviewCodeInfo guifg=#9399b3 guibg=#28283d'
vim.cmd.hi 'MarkviewInlineCode guibg=#32324c'
vim.cmd.hi 'MarkviewIcon1 guifg=#f38ba9 guibg=#28283d'
vim.cmd.hi 'MarkviewIcon1Sign guifg=#f38ba9'
vim.cmd.hi 'MarkviewIcon1Fg guifg=#f38ba9'
vim.cmd.hi 'MarkviewIcon2 guifg=#fab388 guibg=#28283d'
vim.cmd.hi 'MarkviewIcon2Sign guifg=#fab388'
vim.cmd.hi 'MarkviewIcon2Fg guifg=#fab388'
vim.cmd.hi 'MarkviewIcon3 guifg=#f9e2b0 guibg=#28283d'
vim.cmd.hi 'MarkviewIcon3Sign guifg=#f9e2b0'
vim.cmd.hi 'MarkviewIcon3Fg guifg=#f9e2b0'
vim.cmd.hi 'MarkviewIcon4 guifg=#a6e3a2 guibg=#28283d'
vim.cmd.hi 'MarkviewIcon4Sign guifg=#a6e3a2'
vim.cmd.hi 'MarkviewIcon4Fg guifg=#a6e3a2'
vim.cmd.hi 'MarkviewIcon5 guifg=#74c7ed guibg=#28283d'
vim.cmd.hi 'MarkviewIcon5Sign guifg=#74c7ed'
vim.cmd.hi 'MarkviewIcon5Fg guifg=#74c7ed'
vim.cmd.hi 'MarkviewIcon6 guifg=#b4beff guibg=#28283d'
vim.cmd.hi 'MarkviewIcon6Sign guifg=#b4beff'
vim.cmd.hi 'MarkviewIcon6Fg guifg=#b4beff'
vim.cmd.hi 'MarkviewCheckboxUnchecked guifg=#f38ba9'
vim.cmd.hi 'MarkviewCheckboxProgress guifg=#cba6f8'
vim.cmd.hi 'MarkviewCheckboxPending guifg=#f9e2b0'
vim.cmd.hi 'MarkviewCheckboxChecked guifg=#a6e3a2'
vim.cmd.hi 'MarkviewCheckboxCancelled guifg=#9399b3'
vim.cmd.hi 'MarkviewBlockQuoteWarn guifg=#f9e2b0'
vim.cmd.hi 'MarkviewBlockQuoteSpecial guifg=#cba6f8'
vim.cmd.hi 'MarkviewBlockQuoteOk guifg=#a6e3a2'
vim.cmd.hi 'MarkviewBlockQuoteNote guifg=#89b4fb'
vim.cmd.hi 'MarkviewBlockQuoteError guifg=#f38ba9'
vim.cmd.hi 'MarkviewBlockQuoteDefault guifg=#9399b3'
vim.cmd.hi 'MarkviewCheckboxStriked cterm=strikethrough gui=strikethrough guifg=#9399b3'
