alias vim = nvim
alias vi = nvim
alias t = tmux
alias te = tmux kill-session and exit
#alias ls = exa
#alias ll = exa --long
#alias tree = exa --tree
#alias la = exa --all
alias la = ls -a
#alias lla = exa --long --all
alias cat = bat
alias zz = cd -
alias lg = lazygit
alias :q = exit
alias cl = clear
alias killme = shutdown now
